### ISSUE TITLE
运行“prcdns --host 127.0.0.1 --port 5330 --tcp_udp tcp --proxy 127.0.0.1:1080”遇错

### ISSUE THREAD

**Issue by luckypoem** [lbp0200/prc-dns#6]
hi.

yudeMacBook-Air:prc-dns-by-lbp0200 brite$  prcdns --host 127.0.0.1 --port 5330 --tcp_udp tcp --proxy 127.0.0.1:1080
DNS Server start running at tcp 127.0.0.1:5330
Traceback (most recent call last):
  File "/usr/local/bin/prcdns", line 9, in <module>
    load_entry_point('prc-dns==0.0.1', 'console_scripts', 'prcdns')()
  File "build/bdist.macosx-10.12-intel/egg/prcdns/index.py", line 499, in main
  File "/Library/Python/2.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
yudeMacBook-Air:prc-dns-by-lbp0200 brite$

如何解决？谢谢回复

**Comment by lbp0200** [comment]
自动获取当前公共ip错误，
加上参数--myip 试试吧

可以通过这个网站找到自己的ip，https://www.ipip.net/ip.html

**Comment by luckypoem** [comment]
我重装了一次这个prc-dns,这次运行prcdns --host 127.0.0.1 --port 5330 --tcp_udp tcp --proxy 127.0.0.1:1080没有出错，但是根本解析不了主机名。我在浏览器里，无论访问国内域名或国外域名都不行。你确认你运行命令prcdns --host 127.0.0.1 --port 5330 --tcp_udp tcp --proxy 127.0.0.1:1080后，你的浏览器能打开ip.cn或ip-adress.com这样的网站吗
